### ISSUE TITLE
Mettre a jour gitignore ?

### ISSUE THREAD

**Issue by GuillaumeBelz** [DigitalPulseSoftware/NazaraEngine#100]
Le fichier `.gitignore` n'est pas vraiment standard, pourquoi ignorer les fichiers objets qui sont dans `build` par exemple et pas tous les fichiers objets ? Même si la configuration de premake fait que les fichiers objets devraient être dans `build`, il n'y a pas trop de raison de ne pas ignorer les fichiers objets qui serait par erreur (ou configuration différente) ailleurs.

**Comment by DPSLynix** [comment]
Il y a deux raisons à cela.

La première est de détecter plus facilement certaines erreurs, si un fichier se retrouve à un endroit où il n'est pas censé être, git le signalera plutôt que l'ignorer (et de laisser un fichier inutile au mauvais endroit).  
La seconde est que certains fichiers binaires sont commit dans le repo, je pense aux .dll, .so et (à venir) .dynlib des dépendances externes se trouvant dans extlibs/, il faudra donc de toute façon ignorer certaines extensions par dossier, et cela devient plus logique d'ignorer tous les fichiers générés par la compilation de la même façon.

Quant à l'aspect non-standard, je ne pense pas que ça soit justifié, dans la mesure  où ce bloc:
```
# DocProject is a documentation generator add-in
DocProject/buildhelp/
DocProject/Help/*.HxT
DocProject/Help/*.HxC
DocProject/Help/*.hhc
DocProject/Help/*.hhk
DocProject/Help/*.hhp
DocProject/Help/Html2
DocProject/Help/html
```

provient du [.gitignore de référence pour Visual Studio](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore).
