### ISSUE TITLE
Add serialization to SDK (including loading a Ndk::World from file)

### ISSUE THREAD

**Issue by SirLynix** [DigitalPulseSoftware/NazaraEngine#107]
Now that Nazara has a working ECS, we should upgrade it to the next step and give it a proper serialization feature.

We aim to have this kind of code:
```cpp
world.SaveToFile("save.nwf"); // Nazara World File, for example
```

along with

```cpp
world.LoadFromFile("save.nwf"); // Restores entities with their components and world systems
```

A nice feature to add to that system would be some kind of addons:  
```cpp
world.RegisterDataSection("SomeNameToPreventConflicts", <load function>, <save function>);
```

This could also allow users to override Nazara default save/load functions.

**Comment by testlalaalla123123** [comment]
b
