### ISSUE TITLE
Problem with states and enabling entities

### ISSUE THREAD

**Issue by Jejeleterrible** [DigitalPulseSoftware/NazaraEngine#115]
Hello,
In my program I've got a state where, in the constructor, I create the entities.

``` cpp
StateEarth::StateEarth(/*args...*/)
{
	m_camera = m_world->CreateEntity();
        m_ground = m_world->CreateEntity();
	m_light = m_world->CreateEntity();
        //Initialize all components, etc...
}
```

Then, In `Enter()`, I enable all entities : 

``` cpp
m_camera->Enable(true);
m_ground->Enable(true);
m_light->Enable(true);
```

Finally, in `Leave()`, I disable the entities : 

``` cpp
m_camera->Enable(false);
m_ground->Enable(false);
m_light->Enable(false);
```

And, guess what ? It doesn't work :D 

In fact, the game crashes at runtime. But if I "commentarize" all these "Enable" instructions, it doesn't crash.

**Comment by DrLynix** [comment]
Please post your code or a minimal code to reproduce the problem, a WIP demo I'm working on uses the state system without any trouble.

Also, where does it crashes?
