### ISSUE TITLE
Message à chaque création de buffer où celui-ci se trouvait en mémoire

### ISSUE THREAD

**Issue by r00tKiller** [DigitalPulseSoftware/NazaraEngine#120]
[Screenshot](https://puu.sh/ukDRc/2252006d8f.png)

> C'est dû au contexte OpenGL debug, les drivers Nvidia se sont crus malin d'informer à chaque création de buffer où celui-ci se trouvait en mémoire (ce n'est donc pas une erreur en soi). 
> 
> Tu n'auras pas ça en Release, mais il faut que je bloque ça en débug, n'hésite pas à faire une issue sur GitHub :)

**Comment by r00tKiller** [comment]
Mais du coup si c'est juste des messages de "debug", pourquoi ça tourne à moins de 20 fps ?

**Comment by DrLynix** [comment]
Parce que chaque "warning" va écrire dans le fichier de log, ce qui est une opération lente.

**Comment by r00tKiller** [comment]
Ggwp
