### ISSUE TITLE
Prerequesites.hpp => Prerequisites.hpp

### ISSUE THREAD

**Issue by germinolegrand** [DigitalPulseSoftware/NazaraEngine#152]
First of all, the name includes a typo.
Secondly why not having a Config.hpp instead, like you have in every modules ? That would be a simpler name, and would enhance consistency.

Regards,

**Comment by DrLynix** [comment]
Fixed by merging your PR, thank you.

I prefer to keep Config.hpp and Prerequisites.hpp separated because they have a different purpose, as Prerequisites.hpp is agnostic to the module or tool being compiled (unlike Config.hpp headers which are very specifics).
