### ISSUE TITLE
compilation erreur ' addrinfoW '

### ISSUE THREAD

**Issue by shadesmonde** [DigitalPulseSoftware/NazaraEngine#157]
salut. la compilation plante a cause de " error: 'addrinfoW' does not name a type "
dans IpAddressImpl.hpp

**Comment by DrLynix** [comment]
Bonjour,

Quel compilateur utilises-tu ?

**Comment by shadesmonde** [comment]
Bonjour, 

j'utilise MinGW 6.3

**Comment by DrLynix** [comment]
Le support de Windows Vista et plus est défaillant sur MinGW (même si ça dépend des distributions), tu peux donc désactiver l'utilisation des fonctions NT6 en modifiant le fichier Nazara/Core/Config.hpp, tu cherches la ligne:
```cpp
#define NAZARA_CORE_WINDOWS_NT6 1
```

Tu changes le 1 en zéro et tu effectues une recompilation complète, ça devrait dès lors fonctionner :)

**Comment by shadesmonde** [comment]
Merci, cependant j'ai encore plusieurs erreur ; 

> Nazara\Network\Win32\SocketImpl.cpp|22|fatal error: Mstcpip.h: No such file or directory|
Nazara\Network\Win32\IpAddressImpl.cpp|328|error: 'ERROR_NOT_ENOUGH_MEMORY' was not declared in this scope|
Nazara\Network\Win32\SocketPollerImpl.cpp||In member function 'bool Nz::SocketPollerImpl::IsReadyToRead(Nz::SocketHandle) const':|
Nazara\Network\Win32\SocketPollerImpl.cpp|40|error: invalid conversion from 'const fd_set*' to 'fd_set*' [-fpermissive]|
mingw\include\winsock.h|137|note:   initializing argument 2 of 'int __FD_ISSET(SOCKET, fd_set*)'|
Nazara\Network\Win32\SocketPollerImpl.cpp||In member function 'bool Nz::SocketPollerImpl::IsReadyToWrite(Nz::SocketHandle) const':|
Nazara\Network\Win32\SocketPollerImpl.cpp|49|error: invalid conversion from 'const fd_set*' to 'fd_set*' [-fpermissive]|
mingw\include\winsock.h|137|note:   initializing argument 2 of 'int __FD_ISSET(SOCKET, fd_set*)'|
Nazara\Network\Win32\SocketPollerImpl.cpp||In member function 'bool Nz::SocketPollerImpl::IsRegistered(Nz::SocketHandle) const':|
Nazara\Network\Win32\SocketPollerImpl.cpp|58|error: invalid conversion from 'const fd_set*' to 'fd_set*' [-fpermissive]|
mingw\include\winsock.h|137|note:   initializing argument 2 of 'int __FD_ISSET(SOCKET, fd_set*)'|
Nazara\Network\Win32\SocketPollerImpl.cpp|59|error: invalid conversion from 'const fd_set*' to 'fd_set*' [-fpermissive]|
mingw\include\winsock.h|137|note:   initializing argument 2 of 'int __FD_ISSET(SOCKET, fd_set*)'|

**Comment by DrLynix** [comment]
Je viens de faire un correctif pour ces erreurs, pourrais-tu pull et réessayer de compiler ?

**Comment by shadesmonde** [comment]
il me reste c'est 2 erreur : 

> Nazara\NazaraEngine-master\src\Nazara\Network\Win32\SocketImpl.cpp|22|fatal
 error: Mstcpip.h: No such file or directory|
Nazara\NazaraEngine-master\src\Nazara\Network\Win32\IpAddressImpl.cpp|333|error: 'ERROR_NOT_ENOUGH_MEMORY' was not declared in this scope|

**Comment by DrLynix** [comment]
Tu utilises quelle version de MinGW plus précisément ?

**Comment by shadesmonde** [comment]
MinGW 6.3.0

**Comment by DrLynix** [comment]
Ça ne suffit pas comme information, il existe plein de versions différentes de MinGW (sans parler de la version de GCC), la TDM, la w64, etc.
En clair, où as-tu téléchargé ta distribution de MinGW ?

**Comment by shadesmonde** [comment]
MinGw installation manager trouver ici " https://sourceforge.net/projects/mingw/files/Installer/"  puis j'ai installer mingw32-gcc-g++ en version 6.3.0-1 et mingw32-base version 2013072200

**Comment by DrLynix** [comment]
Ce dernier correctif devrait résoudre le problème d'une façon un peu plus générique pour MinGW du coup.

**Comment by shadesmonde** [comment]
ça marche nickel. merci beaucoup :)
