### ISSUE TITLE
Using SDL2 instead of native windowing APIs

### ISSUE THREAD

**Issue by Krenodeno** [DigitalPulseSoftware/NazaraEngine#182]
This discussion is about whether switching to the windowing lib **SDL2** or sticking to **own implementation** of windowing for multiple platforms like _Windows_, _Xorg_, _Wayland_ and so on...

The SDL library provide a lot of functionnality so we would stick to **windowing** and **inputs** (keyboard/joystick)

Pros:
-
Cons:
-

**Comment by Gawaboumga** [comment]
More questions:

- Should we integrate the sources of the SDL modules that interest us (only windowing and input) or have to make a DLL ? (Taking into account the OS, obviously that under Linux it is easier to install the package)
- Is it interesting to provide a replacement backend if the SDL is absent ?
- Should SDL generates the OpenGL context in Renderer for us ?

**Comment by SirLynix** [comment]
This has been done, Nazara now uses SDL2 as its windowing and inputs backend.

> Should we integrate the sources of the SDL modules that interest us (only windowing and input) or have to make a DLL ? (Taking into account the OS, obviously that under Linux it is easier to install the package)

Nazara-Next now relies on xmake which handles external libraries for us and will download/compile SDL2 if not found on the system.

> Is it interesting to provide a replacement backend if the SDL is absent ?

See previous answer

> Should SDL generates the OpenGL context in Renderer for us ?

I think not, as Nazara can benefit from fine-tuning the OpenGL context creation.
