### ISSUE TITLE
Premake4 bug with gmake generator, same-named files result in same-named target

### ISSUE THREAD

**Issue by danman5555** [DigitalPulseSoftware/NazaraEngine#19]
There is a problem with the premake4's gmake generator in version 4.4-beta4, same-named files such as PCX/Loader.cpp and STB/Loader.cpp are compiled into the same object file, and as a result the last file compiled erases the others, and it links several times instead of only once.

Here is some extracts from the generated NazaraUtility.make file:

```
74 OBJECTS := \
[...]
111     $(OBJDIR)/Parser.o \
112     $(OBJDIR)/Loader.o \
113     $(OBJDIR)/Loader.o \
114     $(OBJDIR)/Loader.o \
115     $(OBJDIR)/Parser.o \
116     $(OBJDIR)/Loader.o \
```

```
292 $(OBJDIR)/Loader.o: ../../src/Nazara/Utility/Loaders/MD5Anim/Loader.cpp
293     @echo $(notdir $<)
294     $(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
295 $(OBJDIR)/Loader.o: ../../src/Nazara/Utility/Loaders/STB/Loader.cpp
296     @echo $(notdir $<)
297     $(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -MF $(@:%.o=%.d) -c "$<"
298 $(OBJDIR)/Loader.o: ../../src/Nazara/Utility/Loaders/PCX/Loader.cpp
299     @echo $(notdir $<)
```

I've tried the premake-dev, as mentionned here : http://industriousone.com/topic/premake-gmake-issue-same-named-files-result-same-named-targets#comment-21419. 

The generated makefile now looks like that : 
```
 84     $(OBJDIR)/Loader1.o \
 85     $(OBJDIR)/Parser.o \
 86     $(OBJDIR)/Loader2.o \
 87     $(OBJDIR)/Parser1.o \
 88     $(OBJDIR)/Loader3.o \
 89     $(OBJDIR)/Loader4.o \
```

So using premake-dev version ( https://bitbucket.org/premake/premake-dev ) fixes the problem.

**Comment by DPSLynix** [comment]
I'm closing this since I've updated to premake-dev.
