### ISSUE TITLE
The Scene API has to be remade.

### ISSUE THREAD

**Issue by DPSLynix** [DigitalPulseSoftware/NazaraEngine#34]
The current Scene API is stuck between the modern way of creating nodes (Scene::CreateNode) and the old way (Node::SetParent), because neither of them is perfect.

1) How to handle nodes children with the modern way?
2) How to handle non-scene node parenting with the modern way?
3) How to handle scenes in the NDK (Nazara Development Kit)? I think the Scene API should not be a part of Nazara but a part of it's SDK, because a sound emitter should be able to be part of the scene as a node, same goes for a model and a physical object.

Which leads us to
4) How to handle models/sprite/text rendering in Nazara without scenes? Should we expose/impose the low-level API (i.e. render queues, culling and such)?
5) If so, why would one use Nazara without it's SDK?

I think we have to prepare Nazara for the beta before thinking of this.

**Comment by Overdrivr** [comment]
What about the scene inheriting node, and Node having a AttachChild method
? To me it feels like the scene api should be part of nazara, not the sdk.

 Le 25 janv. 2015 17:11, "Jérôme Leclercq" <notifications@github.com> a
écrit :

**Comment by DPSLynix** [comment]
I though of it, it only sloves the first problem, still no way of handling non-scene nodes.

I really feel like Nazara should be divided in two parts, the lower-level libraries (the current Nazara Engine) which would only gives algorithms without forcing any architecture, that would be the SDK which would complete Nazara as a "game engine", allowing you to create games very easily with a specified architecture, and tools.

The good thing is that the hardest part has already been made, now it's time to work on the SDK.

**Comment by Overdrivr** [comment]
What's a non-scene node ?

**Comment by DPSLynix** [comment]
Cameras, sound nodes, etc.

**Comment by Overdrivr** [comment]
Ah allright I understand. Well, to me it's definitely scene nodes, except they are not related to rendering. What bothers you with that approach ?

**Comment by DPSLynix** [comment]
NzScene : NazaraGraphics
NzSound : NazaraAudio

They don't know each other.

I'm starting to make a Entity Component System to replace the scenes, into the SDK, it should solve those problems.

**Comment by DPSLynix** [comment]
This is currently being resolved in the NDK branch
