### ISSUE TITLE
Visual Studio 2013 not supported

### ISSUE THREAD

**Issue by GigAnon** [DigitalPulseSoftware/NazaraEngine#52]
Premake does generate solutions for Visual Studio 2013, but compilation fails with "Nazara requires a C++11 compliant compiler".

After a quick check in Prerequisites.hpp, I found:

#define NAZARA_COMPILER_SUPPORTS_CPP11 (_MSC_VER >= 1900)

VS13 is bundled with MSVC 18. I assume Nazara needs VS15 (since the compilation fails spectacularly with _MSC_VER >= 1800), but it means premake needs to be upgraded to version 5.

EDIT: using premake5 out of the box seems to be breaking compatibility with Code::Blocks... Were the premake4 files in the depot modified to include the relevant action?

**Comment by DPSLynix** [comment]
Hi,

Yes, Nazara requires VS15 sinces it's the first version of the compiler to supports enough C++11 features to build the engine.

The Visual Studio 2013 build is only provided to be used by Visual Studio 2015 (needs a retarget action).
Switching to premake5 is a good idea, but it's still a work in progress and doesn't support CodeBlocks anymore (for this reason I think I will provide a CodeBlocks target myself).

I'm leaving this open until fixed.

**Comment by Overdrivr** [comment]
Are you sure you still want to stick to premake and not give a try at [Gradle](http://gradle.org/) ? It is an automation system (with build plugins). To compile C++ the only requirement for the user is to have a c++ compiler available on the PATH.

I have used it successfully on [ZNoise](https://github.com/Overdrivr/ZNoise), I can now control entirely the build process without too much effort, I can generate multiple executables. I have also used it on [Telemetry](https://github.com/Overdrivr/Telemetry) where I produce one executable for examples and one for testing.

I am not tied anymore to an IDE, and I can now use awesome text editors like Atom or Sublime, and recompile the entire library with a single command from a terminal. 

And it's also an automation system, so if you want to automate some stuff as the project grows bigger, it is specifically designed for that.

It is also highly portable, and free, and open-source. It is used within Android Studio to control the build process for all Android apps.

**Comment by DPSLynix** [comment]
Hi, sorry to answer this late, I didn't see your answer.

I took a look at Gradle, and even though it looks simpler, it also looks rather limited (it looks like you're only allowing GCC toolset, premake has no such limitation).

Premake also allows you to use Lua, which can be used for anything, and is already used for generating headers, and soon turning Unicode data into C++ data files.

And of course it's as portable and free and open-source as you wish :stuck_out_tongue: 

I have no reason to switch to another build system for now.

**Comment by DPSLynix** [comment]
Btw, this issue has been closed with the inclusion of premake-5 binaries

**Comment by Overdrivr** [comment]
Well, I doubt Gradle can be labeled as limited.

I am enforcing GCC on my projects, but it actually supports more compilers than premake. See 72.3.
 
https://docs.gradle.org/current/userguide/native_software.html
versus
https://github.com/premake/premake-core/wiki/What-Is-Premake#key-features

I use gradle in this [project](https://github.com/Overdrivr/Telemetry) to support a rather complex build system.

https://github.com/Overdrivr/Telemetry/blob/master/BUILD.md

Using Gradle, I am able to perform a C and C++ compilation of the library, perform tests on the core, then prepare and assemble files for four different distributions (Mbed, Arduino, pure C, pure C++), generate a file containing some test vectors, run integration tests on all distributions, pack distributions to a zip file. 
Doing all of that just from a terminal with a few commands is pretty neat  :) And it's ideal for continouus integration, highly reproducible builds

However, I do agree with you, all of the above can probably be done using premake/lua.

One reason Gradle is interesting for Nazara is the support for hierarchical builds, which is just ideal for a module system.

Each module would define its own build.gradle file, then top project would just need to git clone modules, and it would immediately be able to build the entire thing, without configuration nor fiddling around.

Anyway, I also understand you may not want to migrate. In case you are interested for trying things a little bit, I could write some build.gradle file inside my fork. Let me know ;)

**Comment by DPSLynix** [comment]
Well Premake 5 is in developpement actually, it supported much more targets
back in version 4 and it's improving (which is the reason I include both
versions for now).

Gradle does not interest me that much for some reasons, the first one is
that the current build system works well and has no limitation that's
bothering me, the second is that Premake uses Lua which is one easy and
spread language used by Nazara. Using Gradle (Or even CMake) would require
anyone to handle another language they may not know.

The current system doesn't handle hierarchical builds but I don't have the
feeling it should.
Currently, a module require a .lua file to describe its files, it takes
about five lines and is easy to understand/write, and that's all it
requires, building via premake (which doesn't require
configuration/fiddling neither) then takes the new module file into account
and Voilà!

(On a side note, look at this example of premake code
<https://github.com/premake/premake-core/blob/master/scripts/package.lua>,
it's used to embed source/binaries and comes from the original repo)

Thank you for your offer, but switching to another building system is not
something that will happen in the short time as Premake is working great
and Gradle/CMake have no key feature that Premake doesn't have :)

2016-03-08 14:48 GMT+01:00 Rémi Bèges <notifications@github.com>:

**Comment by Overdrivr** [comment]
Didn't know about difference between Premake 4/5.

Ok I understand everything, just thought of sharing a tool I enjoy at the moment ;)

About hierarchical builds, my statement was more in the idea of "adding a module just by git clone a repo". But if you feel the current system allows you to do things just as easily then yes no reason to migrate a build system that works and you feel comfortable with.

**Comment by DPSLynix** [comment]
Actually it's already working that way since the beginning, the build
script I made will explore all the .lua files in some key directories (as
build/module) and gather informations in a specified way.

2016-03-08 15:09 GMT+01:00 Rémi Bèges <notifications@github.com>:
