### ISSUE TITLE
Crash in initializer

### ISSUE THREAD

**Issue by MehdiBmm** [DigitalPulseSoftware/NazaraEngine#56]
This piece of code that initialize the engine makes it crash:
`#include <Nazara/Core/Clock.hpp> // Horloges
#include <Nazara/Graphics.hpp> // Module graphique
#include <Nazara/Renderer.hpp> // Module de rendu
#include <Nazara/Utility.hpp> // Module utilitaire
#include <NDK/Components/CameraComponent.hpp>
#include <NDK/Components/GraphicsComponent.hpp>
#include <NDK/Components/LightComponent.hpp>
#include <NDK/Components/NodeComponent.hpp>
#include <NDK/Systems/RenderSystem.hpp>
#include <NDK/Sdk.hpp>
#include <NDK/World.hpp>
#include <iostream>

int main()
{
   Nz::Initializer<Ndk::Sdk> nazara;
	if (!nazara)
	{
		// Une erreur s'est produite dans l'initialisation d'un des modules
		std::cout << "Failed to initialize Nazara, see NazaraLog.log for further informations" << std::endl;
		std::getchar(); // On laise le temps de voir l'erreur

		return EXIT_FAILURE;
	}

    return 0;
}
`
Compiled in code::blocks with GGC nuwen (c++14 compliant) and in x64 debug mode.
![errorrr](https://cloud.githubusercontent.com/assets/17619261/13499132/3edf6812-e15d-11e5-8262-4e71cb9cc89c.png)

**Comment by DPSLynix** [comment]
Try to remove the `thread_local` keyword in [Directory.cpp](https://github.com/DigitalPulseSoftware/NazaraEngine/blob/master/src/Nazara/Core/Directory.cpp#L34), it was the cause of the previous crash.

If it fixes the crash, it means the bug is coming from your MinGW distribution and I cannot fix it, just get around it.

**Comment by MehdiBmm** [comment]
thread_local keyword removed in src/Nazara/Core/Directory.cpp as told but it's still crashing.

**Comment by DPSLynix** [comment]
This was the cause of the previous crash on MinGW, but looking at that I don't know.

What compiler distribution are you using (in order to debug on my own)?

**Comment by MehdiBmm** [comment]
MingW [nuwen distrib](http://nuwen.net/mingw.html), last version of that website, along with the last stable release of Code::Blocks under Windows 10.

**Comment by DPSLynix** [comment]
Is this still an issue?

**Comment by MehdiBmm** [comment]
Didn't check that out since I made this query, I have absolutely no idea as I switched to Ubuntu ;)

**Comment by DPSLynix** [comment]
Well that's a good thing Linux now runs on Ubuntu! :)

**Comment by DPSLynix** [comment]
Well that's a good thing Nazara now runs on Ubuntu! :)

**Comment by MehdiBmm** [comment]
Oh, I should check that out :D is there a guide or something to get started ?

**Comment by DPSLynix** [comment]
Well, in french:
https://github.com/DigitalPulseSoftware/NazaraEngine/wiki/(FR)-Tutoriel-00---Introduction

2016-06-08 15:53 GMT+02:00 MehdiBmm <notifications@github.com>:

**Comment by MehdiBmm** [comment]
Thankx folk ! ;)
