### ISSUE TITLE
Exception in the detructor of `PhysObject` 

### ISSUE THREAD

**Issue by Bouli1515** [DigitalPulseSoftware/NazaraEngine#60]
The destructor of `PhysObject` throws an exception "Violation d'accès lors de l'exécution à l'emplacement 0x000000FF." (sorry my vs2015 speaks french). 

```
PhysObject::~PhysObject()
{
		if (m_body)
			NewtonDestroyBody(m_world->GetHandle(), m_body); //-> My debugger shows this line.
}
```

**Comment by DPSLynix** [comment]
Do you have any physics component in your scene?

**Comment by Bouli1515** [comment]
No I have just crated a `Ndk::CollisionComponent` with a `Nz::BoxGeom` but without a `Ndk::PhysicsComponent`, like this : 
~~~C++
    auto ballCollisionBox = Nz::BoxGeom::New(Nz::Vector3f(30.f, 30.f, 0.f));
	ball->AddComponent<Ndk::CollisionComponent>(ballCollisionBox);
~~~

**Comment by DPSLynix** [comment]
There's not much I can do about this crash since it happens in an external library, maybe upgrading it would fix the problem :)

**Comment by DPSLynix** [comment]
Is this still an issue since Newton's update?
