### ISSUE TITLE
Problème de compilation code::blocks 16.01

### ISSUE THREAD

**Issue by ImperatorS79** [DigitalPulseSoftware/NazaraEngine#63]
La compilation plante à cause de IpAddressImpl.hpp : 

||=== Build: DebugDynamic in NazaraEngine (compiler: GNU GCC Compiler) ===|
..\..\..\src\Nazara\Network\Win32\IpAddressImpl.hpp|20|error: 'addrinfoW' does not name a type|
||=== Build finished: 1 error(s), 0 warning(s) (0 minute(s), 44 second(s)) ===|
||=== Run: DebugDynamic in NazaraEngine (compiler: GNU GCC Compiler) ===|

OS : Windows 10, 7
Code::blocks 16.01

**Comment by DPSLynix** [comment]
Fixed by 71b562c6365f3fa29150606ba6ebddcef8caef9b :)
