### ISSUE TITLE
Autres problèmes de compilation code::blocks 16.01

### ISSUE THREAD

**Issue by ImperatorS79** [DigitalPulseSoftware/NazaraEngine#65]
Un problème dans IpAddressImpl.cpp

||=== Générer: DebugDynamic in NazaraEngine (compiler: GNU GCC Compiler) ===|
C:\Users\Maryse Hoebeke\Documents\CB_project\NazaraEngine-master\src\Nazara\Network\Win32\IpAddressImpl.cpp|95|error: 'struct in6_addr' has no member named 'u'|
C:\Users\Maryse Hoebeke\Documents\CB_project\NazaraEngine-master\src\Nazara\Network\Win32\IpAddressImpl.cpp|149|error: 'const struct in6_addr' has no member named 'u'|
C:\Users\Maryse Hoebeke\Documents\CB_project\NazaraEngine-master\src\Nazara\Network\Win32\IpAddressImpl.cpp|241|error: 'struct in6_addr' has no member named 'u'|
C:\Users\Maryse Hoebeke\Documents\CB_project\NazaraEngine-master\src\Nazara\Network\Win32\SocketImpl.cpp|9|fatal error: Mstcpip.h: No such file or directory|
||=== Build échoué: 4 error(s), 0 warning(s) (0 minute(s), 7 second(s)) ===|

Corrigé en rajoutant manuellement Mstcpip.h mais deux nouvelles erreurs dues à ce nouveau fichier:

||=== Générer: DebugDynamic in NazaraEngine (compiler: GNU GCC Compiler) ===|
C:\Program Files (x86)\CodeBlocks\MinGW\include\Mstcpip.h|9|fatal error: _mingw_unicode.h: No such file or directory|
C:\Users\Maryse Hoebeke\Documents\CB_project\NazaraEngine-master\src\Nazara\Network\Win32\IpAddressImpl.cpp|95|error: 'struct in6_addr' has no member named 'u'|
C:\Users\Maryse Hoebeke\Documents\CB_project\NazaraEngine-master\src\Nazara\Network\Win32\IpAddressImpl.cpp|149|error: 'const struct in6_addr' has no member named 'u'|
C:\Users\Maryse Hoebeke\Documents\CB_project\NazaraEngine-master\src\Nazara\Network\Win32\IpAddressImpl.cpp|241|error: 'struct in6_addr' has no member named 'u'|
||=== Build échoué: 4 error(s), 0 warning(s) (0 minute(s), 1 second(s)) ===|

||=== Générer: DebugDynamic in NazaraEngine (compiler: GNU GCC Compiler) ===|
C:\Program Files (x86)\CodeBlocks\MinGW\include\Mstcpip.h|10|fatal error: winapifamily.h: No such file or directory|
C:\Users\Maryse Hoebeke\Documents\CB_project\NazaraEngine-master\src\Nazara\Network\Win32\IpAddressImpl.cpp|95|error: 'struct in6_addr' has no member named 'u'|
C:\Users\Maryse Hoebeke\Documents\CB_project\NazaraEngine-master\src\Nazara\Network\Win32\IpAddressImpl.cpp|149|error: 'const struct in6_addr' has no member named 'u'|
C:\Users\Maryse Hoebeke\Documents\CB_project\NazaraEngine-master\src\Nazara\Network\Win32\IpAddressImpl.cpp|241|error: 'struct in6_addr' has no member named 'u'|
||=== Build échoué: 4 error(s), 0 warning(s) (0 minute(s), 1 second(s)) ===|

Corrigé en rajoutant manuellement _mingw_unicode.h et winapifamily.h

Mais cela n'a corrigé que les erreurs d'include, pas les autres 

||=== Build: DebugDynamic in NazaraEngine (compiler: GNU GCC Compiler) ===|
C:\Users\ULg\Desktop\NazaraEngine-master\src\Nazara\Network\Win32\IpAddressImpl.cpp|95|error: 'struct in6_addr' has no member named 'u'|
C:\Users\ULg\Desktop\NazaraEngine-master\src\Nazara\Network\Win32\IpAddressImpl.cpp|149|error: 'const struct in6_addr' has no member named 'u'|
C:\Users\ULg\Desktop\NazaraEngine-master\src\Nazara\Network\Win32\IpAddressImpl.cpp|241|error: 'struct in6_addr' has no member named 'u'|
||=== Build finished: 3 error(s), 0 warning(s) (0 minute(s), 5 second(s)) ===|

OS: WIndows 7, 10
IDE : code::blocks 16.01

**Comment by DPSLynix** [comment]
Quelle tête à la structure in6_addr dans tes headers ?

2016-06-08 14:51 GMT+02:00 ImperatorS79 <notifications@github.com>:

**Comment by ImperatorS79** [comment]
fichier ws2tcpip.h (win7) :
ligne 164
struct in6_addr {
    union {
        u_char	_S6_u8[16];
        u_short	_S6_u16[8];
        u_long	_S6_u32[4];
        } _S6_un;
};

**Comment by DPSLynix** [comment]
Ça devrait être corrigé :)

**Comment by ImperatorS79** [comment]
je n'ai plus que des erreurs de linkage :

||=== Build: DebugDynamic in NazaraEngine (compiler: GNU GCC Compiler) ===|
ld.exe||cannot find -lsndfile-1|
ld.exe||cannot find -llua-s-d|
ld.exe||cannot find -lNewton|
ld.exe||cannot find -lfreetype-s|
ld.exe||cannot find -lstb_image-s-d|
||error: ld returned 1 exit status|
||=== Build failed: 6 error(s), 0 warning(s) (3 minute(s), 49 second(s)) ===|

**Comment by DPSLynix** [comment]
Il n'y a plus que sndfile qui ne soit pas reconnu ?

**Comment by ImperatorS79** [comment]
J'ai rajouté

**..\..\..\extlibs\lib\mingw\x64**
......\extlibs\lib\common\\**x64**

Dans les options du linker et il n'y a que sndfile qui fait encore une erreur

**Comment by DPSLynix** [comment]
C'est extrêmement bizarre, c'est la même dll que j'utilise sous Visual Studio en 64 bits.

En attendant je te recommande de passer en 32 bits, ça devrait passer, je vais passer sous CodeBlocks ce midi pour voir par moi-même.

**Comment by ImperatorS79** [comment]
En x86, plus de problème (il semblerait) avec sndfile mais

||=== Build: DebugDynamic in NazaraEngine (compiler: GNU GCC Compiler) ===|
..\..\..\extlibs\lib\mingw\x86\liblua-s-d.a(ldo.o):ldo.cpp:(.eh_frame+0x67)||undefined reference to `__gxx_personality_v0'|
||error: ld returned 1 exit status|
||=== Build failed: 2 error(s), 0 warning(s) (0 minute(s), 16 second(s)) ===|

**Comment by DPSLynix** [comment]
Ton compilateur n'est pas compatible avec les bibliothèques précompilées,
compile NazaraExtlibs.workscape et recommence :)

2016-06-09 10:23 GMT+02:00 ImperatorS79 <notifications@github.com>:

**Comment by ImperatorS79** [comment]
j'ai dû remplacer un lumits.h par climits.

Maintenant, j'essaie de comprendre pourquoi il ne trouve pas _pclose, _popen.

**Comment by DPSLynix** [comment]
Quel compilateur utilises-tu ? Ça me paraît vraiment étrange, vu que la
majorité du temps que j'ai développé Nazara, c'était avec CodeBlocks.

2016-06-09 10:44 GMT+02:00 ImperatorS79 <notifications@github.com>:

**Comment by ImperatorS79** [comment]
mingw32-g++.exe , mingw32-gcc.exe,   gcc 4.9.2 (de base avec code::blocks 16.01)

**Comment by DPSLynix** [comment]
C'est certainement la version TDM (que tu verras en appellant mingw32-g++
-v), je vais regarder ça ASAP.

2016-06-09 11:34 GMT+02:00 ImperatorS79 <notifications@github.com>:

**Comment by ImperatorS79** [comment]
C:\Program Files (x86)\CodeBlocks\MinGW\bin>mingw32-g++.exe -v
Using built-in specs.
COLLECT_GCC=mingw32-g++.exe
COLLECT_LTO_WRAPPER=C:/Program\ Files\ (x86)/CodeBlocks/MinGW/bin/../libexec/gcc/mingw32/4.9.2/lto-wrapper.exe
Target: mingw32
Configured with: ../../../src/gcc-4.9.2/configure --build=mingw32 --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-graphite --enable-libstdcxx-debug --enable-threads=posix --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libstdcxx-threads --enable-libstdcxx-time --with-gnu-ld --disable-werror --disable-nls --disable-win32-registry --disable-symvers --enable-cxx-flags='-fno-function-sections -fno-data-sections -DWINPTHREAD_STATIC' --prefix=/mingw32tdm --with-local-prefix=/mingw32tdm --with-pkgversion=tdm-1 --enable-sjlj-exceptions --with-bugurl=http://tdm-gcc.tdragon.net/bugs
Thread model: posix
gcc version 4.9.2 **(tdm-1)**

Il semblerait en effet, mais qu'elle est la différence ?

**Comment by DPSLynix** [comment]
Ces binaires utilisent des options qui ne sont pas directement compatibles,
comme par exemple le modèle d'exception (SJLJ, comparé au SEH que je
fournis).

Par contre que ça ne fonctionne pas en recompilant les bibliothèques C++,
ça m'embête, les bibliothèques C devraient rester compatibles.

Je télécharge CB

2016-06-09 12:03 GMT+02:00 ImperatorS79 <notifications@github.com>:

**Comment by DPSLynix** [comment]
Pense à regénérer tes fichiers .workspace avec Premake avant de retenter la compilation :)
