### ISSUE TITLE
Il manque NazaraEngine-d.a sur votre système

### ISSUE THREAD

**Issue by ImperatorS79** [DigitalPulseSoftware/NazaraEngine#66]
Os : Windows 10

Message affiché quand je veux exécuter le tutoriel 1.

**Comment by DPSLynix** [comment]
Il faut l'exécuter depuis CodeBlocks ou bien copier les fichiers .dll de NazaraEngine/lib/mingw/x(86|64) et NazaraEngine/extlibs/lib/mingw/x(86|64) à côté de l'exécutable :)

**Comment by ImperatorS79** [comment]
c'est fait, j'ai la dll de nazara, du ndk, de toutes les libs externes + tous les .A/.lib dans mon dossier

Une petite liste : 
assimp.dll
libsndfile-1.dll
NazaraEngine-d.dll
NazaraSDK-d.dll
Newton.dll
Newton_d.dll
soft_oal.dll
vcruntime140.dll (il me l'a demandé)
libfreetype-s.a
liblibsndfile-1.a
liblua-s.a
liblua-s-d.a
libNazaraEngine-d.a( fichier de 2 mo)
libNazaraSDK-d.a
libstb_image-s.a
libstb_image-s-d.a
assimp.lib
Newton.lib
Newton_d.lib

**Comment by DPSLynix** [comment]
Normalement les .a ne sont nécessaires que pour la compilation, il te
manque quoi du coup ?

Le 9 juin 2016 18:35, "ImperatorS79" <notifications@github.com> a écrit :
>
> c'est fait, j'ai la dll de nazara, du ndk, de toutes les libs externes +
tous les .A/.lib dans mon dossier

**Comment by ImperatorS79** [comment]
Une capture d'ecran
[screen.docx](https://github.com/DigitalPulseSoftware/NazaraEngine/files/307702/screen.docx)

**Comment by DPSLynix** [comment]
Je vois que tu utilises un projet à toi plutôt que les projets CodeBlocks générés par Premake, est-ce que les exemples fonctionnent avec eux ?

**Comment by ImperatorS79** [comment]
Avec les projets premake cela fait ça 
![capture](https://cloud.githubusercontent.com/assets/19779882/15963279/f62caec0-2f10-11e6-8b43-e9b0e5a6f462.PNG)

**Comment by DPSLynix** [comment]
Effectivement certaines dépendances sont build avec Visual C++ 2015 (Newton par exemple), le runtime est donc nécessaire (mais il doit il y avoir moyen de le télécharger sans devoir prendre l'IDE en entier).

Ravi que ton problème soit corrigé, n'hésite pas si tu en rencontres d'autres :)
