### ISSUE TITLE
Deplacer les headers dans include

### ISSUE THREAD

**Issue by GuillaumeBelz** [DigitalPulseSoftware/NazaraEngine#86]
`sndfileLoader.hpp` est dans `src` au lieu de `include`.

https://github.com/DigitalPulseSoftware/NazaraEngine/blob/master/src/Nazara/Audio/Formats/sndfileLoader.hpp 

Voir s'il n'y a pas d'autres headers dans `src` et des sources dans `include`.
Idem pour `Core/Posix`, `Core/Win32` et `Core/Hash`

**Comment by DPSLynix** [comment]
C'est normal, ce header est interne à Nazara et n'est pas exposé aux utilisateurs, c'est la même chose normalement pour tous les headers se trouvant dans le dossier source :)

**Comment by GuillaumeBelz** [comment]
Avoir des headers dans `src` reste contre-intuitif. Le premier réflexe que j'ai eu... est de n'avoir rien fait : je n'avais pas inclue `src` dans la liste des chemins de recherche des headers. Le second réflexe a été de me dire que c'est le bordel.

Mélanger les headers et sources ne posent pas de problème, certaines lib (comme Qt) le font. Par contre, quand on décide de séparer headers et sources, on s'attend pas à trouver des headers dans les sources et réciproquement.
Gérer les headers privées en les mettant dans `src` n'est pas une bonne idée selon moi. Avoir des sous-dossier `private` ou ajouter un suffixe spécifique et gérer cela au deploiement me semble plus clair pour les utilisateurs.

**Comment by DragonJoker** [comment]
Ou tu fais à la FreeType et tu inclus des .c (pas taper, j'ai trouvé ça infâme)
