### ISSUE TITLE
Fichier docx dans include/core

### ISSUE THREAD

**Issue by GuillaumeBelz** [DigitalPulseSoftware/NazaraEngine#87]
https://github.com/DigitalPulseSoftware/NazaraEngine/blob/master/include/Nazara/Core/AbstractLogger.docx

A supprimer ou a deplacer. Si c'est un fichier de template, utiliser un format `txt` plutot que `docx`.

**Comment by DPSLynix** [comment]
C'est un fichier de documentation, pour Doxygen, à voir ce que je vais en faire (peut-être le déplacer dans les sources)

**Comment by GuillaumeBelz** [comment]
Pourquoi `docx` (nom du format de document Word) au lieu de `dox` habituel ?

Il est probable qu'avec le temps, tu ajoutes d'autres fichiers pour la doc (images). Il serait préférable de mettre tout ce qui est spécifique a la génération de la doc dans un répertoire `doc` plutot que dans les sources.

**Comment by DPSLynix** [comment]
Aucune idée sur le pourquoi de cette extension, je vais la changer.

> Il est probable qu'avec le temps, tu ajoutes d'autres fichiers pour la doc (images). Il serait préférable de mettre tout ce qui est spécifique a la génération de la doc dans un répertoire `doc` plutot que dans les sources.

En réalité la documentation fait bien partie du code source, c'est pour ça qu'il me paraît logique que les fichiers liés se retrouvent au même endroit.

**Comment by GuillaumeBelz** [comment]
Et le jour ou tu ajoutes un images ou un graph ou un md ou autre, tu le mettra dans `src` aussi ? Cela serait etrange. 
Du coup, il me semble plus pertinent de créer tout de suite un repertoire pour la doc plutot que d'attendre que ce soit le bazarre dans les sources. (Bien que ca ne sera pas non plus un problème pour corriger plus tard).
