### ISSUE TITLE
Probleme de define avec OpenAL

### ISSUE THREAD

**Issue by GuillaumeBelz** [DigitalPulseSoftware/NazaraEngine#88]
Le fichier `Audio.cpp` utilise des constantes définies dans <AL/al.h> (les constantes commençant par `AL_`). Ce header est inclue dans le projet dans le header `OpenAL.hpp`. La constante `NAZARA_AUDIO_OPENAL` permet d'utiliser ou non OpenAL.

L'utilisation de ces constantes de OpenAL rend le code dépendant de cette lib. Il faut :

- soit rendre cette lib obligatoire et retirer `NAZARA_AUDIO_OPENAL` (mais ca serait une mauvaise idée, cela interdit d'utiliser Nazara sans lib audio).
- soit ajouter un `#else` pour définir ces constantes si OpenAL n'est pas utilisée.
- soit définir de nouvelles constantes indépendantes de la lib audio pour Nazara.

La troisième solution serait la meilleure. EDIT: Ou pas, finalement. En fait, ca serait mieux de rendre le module audio optionnel (voir faire de l'audio un vrai module, c'est a dire pouvoir ajouter ou supprimer l'audio simplement avec un plugin, sans recompiler).

Idem pour les fonctions `al`.
Idem dans `Music.cpp`, `Sound.cpp`, `SoundEffect.cpp`, `SoundEmitter.cpp`...

En fait, OpenAL est une dépendance obligatoire de Nazara ? Il n'est pas possible de build sans ?

**Comment by DPSLynix** [comment]
Si mes souvenirs sont bons (je suis actuellement sur téléphone)  c'est la même chose que pour OpenGL, le define sert à exposer  directement les constantes et fonctions d'OpenAL, ce n'est utile que si quelqu'un veut faire usage d'OpenAL directement, dans le cas contraire la lib reste cachée par Nazara. 

Quant à NazaraAudio, il n'a pas besoin d'OpenAL pour compiler (seulement des headers qui sont fournis par le repo), car il le charge dynamiquement.

**Comment by GuillaumeBelz** [comment]
Sauf que les includes `<AL/al.h>` et `<AL/alc.h>` sont dans le `#ifdef NAZARA_AUDIO_OPENAL`, donc si cette constante n'est pas définie, le projet ne peut pas build.

Peut être qu'il faudrait faire un script qui teste les build avec chaque option activée ou non, pour vérifier qu'une option ne casse pas le build.

**Comment by DPSLynix** [comment]
Ce n'est pas un define optionnel pour la compilation mais pour l'utilisation

**Comment by GuillaumeBelz** [comment]
Ok. Donc mon prédicat de base `La constante NAZARA_AUDIO_OPENAL permet d'utiliser ou non OpenAL` etait faux et pas de problème avec cette issue. Je ferme.
