### ISSUE TITLE
Initialisation des variables membres

### ISSUE THREAD

**Issue by GuillaumeBelz** [DigitalPulseSoftware/NazaraEngine#94]
Initialiser les variables membres lors de leur declaration dans la classe, en particulier pour les types fondamentaux qui peuvent prendre une valeur aléatoire.

Exemple de variable initialisée dans la déclaration :

https://github.com/DigitalPulseSoftware/NazaraEngine/blob/master/include/Nazara/Audio/Music.hpp#L72

Exemple de variable non initialisée dans la déclaration :

https://github.com/DigitalPulseSoftware/NazaraEngine/blob/master/include/Nazara/Renderer/RenderTexture.hpp#L88

**Comment by DPSLynix** [comment]
En réalité l'initialisation des variables membres au niveau de la classe ne fait pas partie de la coding style de Nazara (qu'il faut vraiment que je mette à jour), la raison derrière ce choix est de regrouper toutes les initialisations au même endroit (dans la liste d'initialisation du constructeur), pour plus de facilité de développement et de maintenance.  Et pour éviter de dupliquer les initialisations les constructeurs délégués sont utilisés.

Cependant, bien du code n'est pas encore à jour au niveau de cette norme, je reconnais qu'il y a du travail à faire à ce niveau.

**Comment by GuillaumeBelz** [comment]
Pourquoi regrouper dans la liste d'initialisation (plus de risque d'oubli, plus de maintenance, moins evolutif) plutot que dans la déclaration de la classe ?

**Comment by DPSLynix** [comment]
Parce qu'il est obligatoire d'initialiser certains membres dans la liste d'initialisation de toute façon, alors je suis dans la logique du "autant laisser tout au même endroit" pour l'instant.
