### ISSUE TITLE
Limiter le nombre de lignes dans les fonctiosn

### ISSUE THREAD

**Issue by GuillaumeBelz** [DigitalPulseSoftware/NazaraEngine#95]
Par exemple : ContextImpl::Create(), qui fait presque 200 lignes (commentaires compris).

https://github.com/DigitalPulseSoftware/NazaraEngine/blob/master/src/Nazara/Renderer/GLX/ContextImpl.cpp#L58

Découper le code en fonctions plus simple (respect du SRP ?)

**Comment by DPSLynix** [comment]
Je suis d'accord, certaines fonctions sont trop longues et mériteraient d'être découpées.
