### ISSUE TITLE
Gerer le code plateforme-spécifique par le système de build

### ISSUE THREAD

**Issue by GuillaumeBelz** [DigitalPulseSoftware/NazaraEngine#96]
Par exemple dans Cursor.cpp :

```
#include <Nazara/Utility/Cursor.hpp>

#if defined(NAZARA_PLATFORM_WINDOWS)
    #include <Nazara/Utility/Win32/CursorImpl.hpp>
#elif defined(NAZARA_PLATFORM_X11)
    #include <Nazara/Utility/X11/CursorImpl.hpp>
#else
    #error Lack of implementation: Cursor
#endif
```

Cela peut vite devenir lourd a gérer, surtout si Nazara est portée sur d'autres plateformes (Mac OSX, Android, iOS, Linux Wayland, etc)

Mettre tout le code dans un répertoire spécifique pour chaque plateforme, et utiliser le système de build pour sélectionner le répertoire à utiliser. Dans les sources, ne pas mettre les `#ifdef`.

```
#include <Nazara/Utility/Cursor.hpp>
#include <CursorImpl.hpp>
```

**Comment by DPSLynix** [comment]
Je comprends la logique derrière ça, mais elle me gêne sur certains points:

- Comment gérer les cas où l'implémentation se situe dans plusieurs dossiers (exemple: le code réseau sous Linux est à chercher dans le dossier Linux, mais le reste se trouve dans Posix) ?
- Cela rend la compilation de Nazara encore plus dépendante de son système de build (là où jusqu'ici il suffit de compiler les fichiers sources avec deux ou trois defines et c'est bon).

On peut éventuellement faire un fichier Nazara/Utility/CursorImpl.hpp séparé (dans les sources..) chargé d'inclure le bon header, possiblement auto-généré par premake (de la même façon que les headers globaux du moteur), qu'en penses-tu ?

**Comment by GuillaumeBelz** [comment]
Pour le premier point, tu inclues plusieurs sources. Ou tu crees un posix-shared. C'est pas trop un problème.

Pour le second point, c'est deja depend du build. Tes fichiers sources doivent être inclues ou non en fonction de la plateforme.

Je ne comprends pas pourquoi tu veux gerer cela au niveau des includes, alors que tu dois de toute facon gerer les dependances lors du build. La seule difference, c'est l'organisation des répertoires.

Avant :
```
- Nazara
  - Core
    - Win32
    - Posix
  - Renderer
    - GLX
    - Win32
```

Apres (par exemple) :
```
- Nazara
  - Core
  - Renderer
  - Platforms
    - Win32
    - Posix
```
